spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile}

server:
  port: 8080
  
logging:
  file: /opt/logs/100003173/apollo-portal.log

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP

sagreen:
  key: jw%9h@7M%NF*OEVv
  ivParameter: 6v&d3OtxqrZVAw!9